# Project
modVersion=1.1.1
modGroup=com.carlschierig.advancementdisable
modName=AdvancementDisable
modArchiveName=advancementdisable
modId=advancementdisable
modDescription=Disable mod advancements.
modLicense=LGPL-3.0-only
author=CozyPenguin
# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
# Mod Properties
compatMods=true
# Multiloader
withApiJar=false
withSourcesJar=true
withExampleMod=false
# Modrinth
modrinthId=advancementdisable
# alpha, beta or release
modrinthType=release
curseforgeId=1055905
